# Generated by Django 5.2 on 2025-05-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_usuarios_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
