# Generated by Django 5.2 on 2025-10-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_usuario_data_cadastro_usuario_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_doacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Doação')),
                ('data_doacao', models.DateField(auto_now_add=True, verbose_name='Data da Doação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='polls.usuario')),
            ],
        ),
    ]
